# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('status', models.CharField(max_length=2)),
                ('enabled', models.IntegerField(verbose_name=2)),
                ('real_name', models.CharField(max_length=32)),
                ('qq', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(verbose_name=4)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightRcd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight_data', models.DecimalField(decimal_places=2, max_digits=8)),
                ('record_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wm_app.UserInfo')),
            ],
        ),
    ]
